package routers

import (
	coremicro "JanusGate/controller"
	"JanusGate/struct/publics"

	"github.com/gofiber/fiber/v2"

	//----- SWAGGER -----
	swagger "github.com/arsmn/fiber-swagger/v2"

	// docs are generated by Swag CLI, you have to import them.
	// replace with your own docs folder, usually "github.com/username/reponame/docs"
	_ "JanusGate/docs"
)

func SetupPublicRoutes(app *fiber.App) {
	// Swagger
	app.Get("/docs/*", swagger.HandlerDefault)

	// Endpoints
	apiEndpoint := app.Group("/api")
	publicEndpoint := apiEndpoint.Group("/public")
	v1Endpoint := publicEndpoint.Group("/v1")

	// Service health check
	v1Endpoint.Get("/", publics.CheckServiceHealth)

	// Core Micro Endpoint
	coreEndpoint := v1Endpoint.Group("/coremicro")
	coreEndpoint.Post("/getSavingsForSuperApp", coremicro.SuperAppSaving)
	coreEndpoint.Post("/CallBackReference", coremicro.CallBackReference)
}
