// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "FDSAP Support"
        },
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/public/v1/coremicro/CallBackReference": {
            "post": {
                "description": "Call Back Reference",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "COREMICRO"
                ],
                "summary": "Call Back Reference",
                "parameters": [
                    {
                        "description": "Reference Number",
                        "name": "prNumber",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.PRNumber"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseModel"
                        }
                    }
                }
            }
        },
        "/api/public/v1/coremicro/getSavingsForSuperApp": {
            "post": {
                "description": "Super Saving",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "COREMICRO"
                ],
                "summary": "Super Saving",
                "parameters": [
                    {
                        "description": "Client ID",
                        "name": "cid",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CID"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SuperSaving"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseModel"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "request.CID": {
            "type": "object",
            "properties": {
                "cid": {
                    "description": "Client ID",
                    "type": "integer",
                    "example": 10724585
                }
            }
        },
        "request.PRNumber": {
            "type": "object",
            "properties": {
                "prNumber": {
                    "description": "PR Number",
                    "type": "string",
                    "example": "AAP36467-1638243443748"
                }
            }
        },
        "response.ResponseModel": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "retCode": {
                    "type": "string"
                }
            }
        },
        "response.SuperSaving": {
            "type": "object",
            "properties": {
                "acc": {
                    "type": "string"
                },
                "balance": {
                    "type": "number"
                },
                "centerCode": {
                    "type": "integer"
                },
                "centerName": {
                    "type": "string"
                },
                "cid": {
                    "type": "integer"
                },
                "fullname": {
                    "type": "string"
                },
                "unitCode": {
                    "type": "integer"
                },
                "unitName": {
                    "type": "string"
                },
                "withdrawable": {
                    "type": "number"
                },
                "withdrawalAmount": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost:8000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "JANUS V2",
	Description:      "JANUS Swagger JanusGate",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
