basePath: /
definitions:
  request.Acc:
    properties:
      acc:
        description: Account
        example: 1012-0000-00060776
        type: string
    type: object
  request.CID:
    properties:
      cid:
        description: Client ID
        example: 10724585
        type: integer
    type: object
  request.PRNumber:
    properties:
      prNumber:
        description: PR Number
        example: AAP36467-1638243443748
        type: string
    type: object
  response.CustSavingInfo:
    properties:
      acc: {}
      accDesc:
        type: string
      acctType:
        type: integer
      appType:
        type: integer
      balance:
        type: number
      cid:
        type: integer
      classificationCode:
        type: integer
      classificationType:
        type: integer
      dopen:
        type: string
      status:
        type: integer
    type: object
  response.CustSavingsLists:
    properties:
      acc:
        type: string
      accDesc:
        type: string
      acctType:
        type: integer
      balance:
        type: number
      cid:
        type: integer
      dopen:
        type: string
      status:
        type: integer
      statusDesc:
        type: string
    type: object
  response.ResponseModel:
    properties:
      data: {}
      message:
        type: string
      retCode:
        type: string
    type: object
  response.SuperSaving:
    properties:
      acc:
        type: string
      balance:
        type: number
      centerCode:
        type: integer
      centerName:
        type: string
      cid:
        type: integer
      fullname:
        type: string
      unitCode:
        type: integer
      unitName:
        type: string
      withdrawable:
        type: number
      withdrawalAmount:
        type: number
    type: object
host: localhost:8000
info:
  contact:
    name: FDSAP Support
  description: JANUS Swagger JanusGate
  license: {}
  termsOfService: http://swagger.io/terms/
  title: JANUS V2
  version: "2.0"
paths:
  /api/public/v1/coremicro/callBackReference:
    post:
      consumes:
      - application/json
      description: Call Back Reference
      parameters:
      - description: Reference Number
        in: body
        name: prNumber
        required: true
        schema:
          $ref: '#/definitions/request.PRNumber'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseModel'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ResponseModel'
      summary: Call Back Reference
      tags:
      - CORE MICRO
  /api/public/v1/coremicro/custSavingInfo:
    post:
      consumes:
      - application/json
      description: Customer Savings Information
      parameters:
      - description: Account Number
        in: body
        name: acc
        required: true
        schema:
          $ref: '#/definitions/request.Acc'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CustSavingInfo'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ResponseModel'
      summary: Customer Savings Information
      tags:
      - CORE MICRO
  /api/public/v1/coremicro/customerSavings/:
    post:
      consumes:
      - application/json
      description: Customer Savings List
      parameters:
      - description: Client ID
        in: body
        name: cid
        required: true
        schema:
          $ref: '#/definitions/request.CID'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CustSavingsLists'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ResponseModel'
      summary: Customer Savings List
      tags:
      - CORE MICRO
  /api/public/v1/coremicro/getSavingsForSuperApp:
    post:
      consumes:
      - application/json
      description: Super Saving
      parameters:
      - description: Client ID
        in: body
        name: cid
        required: true
        schema:
          $ref: '#/definitions/request.CID'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SuperSaving'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ResponseModel'
      summary: Super Saving
      tags:
      - CORE MICRO
swagger: "2.0"
